/*
 * @Author: zd
 * @Date: 2022-09-13 15:59:51
 * @LastEditors: zd
 * @LastEditTime: 2022-09-13 16:04:12
 * @Description: 通用字典
 */
const dictionariesMap = {
  Province: [
    { label: '北京市', value: 'BeiJingShi' },
    { label: '天津市', value: 'TianJinShi' },
    { label: '河北省', value: 'HeBeiSheng' },
    { label: '山西省', value: 'ShanXiSheng' },
    { label: '内蒙古自治区', value: 'NeiMengGuZiZhiQu' },
    { label: '辽宁省', value: 'LiaoNingSheng' },
    { label: '吉林省', value: 'JiLinSheng' },
    { label: '黑龙江省', value: 'HeiLongJiangSheng' },
    { label: '上海市', value: 'ShangHaiShi' },
    { label: '江苏省', value: 'JiangSuSheng' },
    { label: '浙江省', value: 'ZheJiangSheng' },
    { label: '安徽省', value: 'AnHuiSheng' },
    { label: '福建省', value: 'FuJianSheng' },
    { label: '江西省', value: 'JiangXiSheng' },
    { label: '山东省', value: 'ShanDongSheng' },
    { label: '河南省', value: 'HeNanSheng' },
    { label: '湖北省', value: 'HuBeiSheng' },
    { label: '湖南省', value: 'HuNanSheng' },
    { label: '广东省', value: 'GuangDongSheng' },
    { label: '广西壮族自治区', value: 'GuangXiZhuangZuZiZhiQu' },
    { label: '海南省', value: 'HaiNanSheng' },
    { label: '重庆市', value: 'ChongQingShi' },
    { label: '四川省', value: 'SiChuanSheng' },
    { label: '贵州省', value: 'GuiZhouSheng' },
    { label: '云南省', value: 'YunNanSheng' },
    { label: '西藏自治区', value: 'XiCangZiZhiQu' },
    { label: '陕西省', value: 'ShanXiShengB' },
    { label: '甘肃省', value: 'GanSuSheng' },
    { label: '青海省', value: 'QingHaiSheng' },
    { label: '宁夏回族自治区', value: 'NingXiaHuiZuZiZhiQu' },
    { label: '新疆维吾尔自治区', value: 'XinJiangWeiWuErZiZhiQu' },
    { label: '台湾省', value: 'TaiWanSheng' },
    { label: '香港特别行政区', value: 'XiangGangTeBieXingZhengQu' },
    { label: '澳门特别行政区', value: 'AoMenTeBieXingZhengQu' },
    { label: '海外', value: 'Overseas' }
  ],
  Overseas: [{ label: '海外', value: 'Overseas' }],
  BeiJingShi: [{ label: '北京市', value: 'BeiJingShi' }],
  TianJinShi: [{ label: '天津市', value: 'TianJinShi' }],
  ShangHaiShi: [{ label: '上海市', value: 'ShangHaiShi' }],
  ChongQingShi: [{ label: '重庆市', value: 'ChongQingShi' }],
  HeBeiSheng: [
    { label: '石家庄市', value: 'ShiJiaZhuangShi' },
    { label: '唐山市', value: 'TangShanShi' },
    { label: '秦皇岛市', value: 'QinHuangDaoShi' },
    { label: '邯郸市', value: 'HanDanShi' },
    { label: '邢台市', value: 'XingTaiShi' },
    { label: '保定市', value: 'BaoDingShi' },
    { label: '张家口市', value: 'ZhangJiaKouShi' },
    { label: '承德市', value: 'ChengDeShi' },
    { label: '沧州市', value: 'CangZhouShi' },
    { label: '衡水市', value: 'HenShuiShi' }
  ],
  ShanXiSheng: [
    { label: '太原市', value: 'TaiYuanShi' },
    { label: '大同市', value: 'DaTongShi' },
    { label: '阳泉市', value: 'YangQuanShi' },
    { label: '长治市', value: 'ChangZhiShi' },
    { label: '晋城市', value: 'JinChengShi' },
    { label: '朔州市', value: 'ShuoZhouShi' },
    { label: '晋中市', value: 'JinZhongShi' },
    { label: '运城市', value: 'YunChengShi' },
    { label: '忻州市', value: 'XinZhouShi' },
    { label: '吕梁市', value: 'LvLiangShi' },
    { label: '临汾市', value: 'LinfenShi' }
  ],
  NeiMengGuZiZhiQu: [
    { label: '呼和浩特市', value: 'HuHeHaoTeShi' },
    { label: '包头市', value: 'BaoTouShi' },
    { label: '乌海市', value: 'WuHaiShi' },
    { label: '赤峰市', value: 'ChiFengShi' },
    { label: '通辽市', value: 'TongLiaoShi' },
    { label: '鄂尔多斯市', value: 'EErDuoSiShi' },
    { label: '呼伦贝尔市', value: 'HuLunBeiErShi' },
    { label: '巴彦淖尔市', value: 'BaYanNaoErShi' }
  ],
  LiaoNingSheng: [
    { label: '沈阳市', value: 'ShenYangShi' },
    { label: '大连市', value: 'DaLianShi' },
    { label: '鞍山市', value: 'AnShanShi' },
    { label: '抚顺市', value: 'FuShunShi' },
    { label: '本溪市', value: 'BenXiShi' },
    { label: '丹东市', value: 'DanDongShi' },
    { label: '锦州市', value: 'JinZhouShi' },
    { label: '营口市', value: 'YingKouShi' },
    { label: '阜新市', value: 'FuXinShi' },
    { label: '盘锦市', value: 'PanJinShi' },
    { label: '铁岭市', value: 'TieLingShi' },
    { label: '朝阳市', value: 'ChaoYangShi' },
    { label: '辽阳市', value: 'LiaoYangShi' },
    { label: '葫芦岛市', value: 'HuLuDaoShi' }
  ],
  JiLinSheng: [
    { label: '长春市', value: 'ChangChunShi' },
    { label: '吉林市', value: 'JiLinShi' },
    { label: '四平市', value: 'SiPingShi' },
    { label: '辽源市', value: 'LiaoYuanShi' },
    { label: '通化市', value: 'TongHuaShi' },
    { label: '白山市', value: 'BaiShanShi' },
    { label: '松原市', value: 'SongYuanShi' },
    { label: '白城市', value: 'BaiChengShi' }
  ],
  HeiLongJiangSheng: [
    { label: '哈尔滨市', value: 'HaErBinShi' },
    { label: '齐齐哈尔市', value: 'QiQiHaErShi' },
    { label: '鸡西市', value: 'JiXiShi' },
    { label: '鹤岗市', value: 'HeGangShi' },
    { label: '双鸭山市', value: 'ShuangYaShanShi' },
    { label: '大庆市', value: 'DaQingShi' },
    { label: '伊春市', value: 'YiChunShi' },
    { label: '佳木斯市', value: 'JiaMuSiShi' },
    { label: '七台河市', value: 'QiTaiHeShi' },
    { label: '黑河市', value: 'HeiHeShi' },
    { label: '绥化市', value: 'SuiHuaShi' },
    { label: '牡丹江市', value: 'MuDanJiangShi' }
  ],
  JiangSuSheng: [
    { label: '南京市', value: 'NanJingShi' },
    { label: '无锡市', value: 'WuXiShi' },
    { label: '徐州市', value: 'XuZhouShi' },
    { label: '常州市', value: 'ChangZhouShi' },
    { label: '苏州市', value: 'SuZhouShi' },
    { label: '南通市', value: 'NanTongShi' },
    { label: '连云港市', value: 'LianYunGangShi' },
    { label: '淮安市', value: 'HuaiAnShi' },
    { label: '盐城市', value: 'YanChengShi' },
    { label: '扬州市', value: 'YangZhouShi' },
    { label: '镇江市', value: 'ZhenJiangShi' },
    { label: '泰州市', value: 'TaiZhouShi' },
    { label: '宿迁市', value: 'SuQianShi' }
  ],
  ZheJiangSheng: [
    { label: '杭州市', value: 'HangZhouShi' },
    { label: '宁波市', value: 'NingBoShi' },
    { label: '温州市', value: 'WenZhouShi' },
    { label: '嘉兴市', value: 'JiaXinShi' },
    { label: '湖州市', value: 'HuZhouShi' },
    { label: '绍兴市', value: 'ShaoXinShi' },
    { label: '金华市', value: 'JinHuaShi' },
    { label: '衢州市', value: 'QuZhouShi' },
    { label: '舟山市', value: 'ZhouShanShi' },
    { label: '丽水市', value: 'LiShuiShi' },
    { label: '台州市', value: 'TaiZhouShi' }
  ],
  AnHuiSheng: [
    { label: '合肥市', value: 'HeFeiShi' },
    { label: '芜湖市', value: 'WuHuShi' },
    { label: '蚌埠市', value: 'BangBuShi' },
    { label: '淮南市', value: 'HuaiNanShi' },
    { label: '马鞍山市', value: 'MaAnShanShi' },
    { label: '淮北市', value: 'HuaiBeiShi' },
    { label: '铜陵市', value: 'TongLingShi' },
    { label: '安庆市', value: 'AnQingShi' },
    { label: '滁州市', value: 'ChuZhouShi' },
    { label: '阜阳市', value: 'FuYangShi' },
    { label: '宿州市', value: 'SuZhouShi' },
    { label: '六安市', value: 'LiuAnShi' },
    { label: '亳州市', value: 'BoZhouShi' },
    { label: '池州市', value: 'ChiZhouShi' },
    { label: '宣城市', value: 'XuanChengShi' },
    { label: '黄山市', value: 'HuangShanShi' }
  ],
  FuJianSheng: [
    { label: '福州市', value: 'FuZhouShi' },
    { label: '厦门市', value: 'XiaMenShi' },
    { label: '莆田市', value: 'PuTianShi' },
    { label: '三明市', value: 'SanMingShi' },
    { label: '泉州市', value: 'QuanZhouShi' },
    { label: '漳州市', value: 'ZhangZhouShi' },
    { label: '南平市', value: 'NanPingShi' },
    { label: '龙岩市', value: 'LongYanShi' },
    { label: '宁德市', value: 'NingDeShi' }
  ],
  JiangXiSheng: [
    { label: '南昌市', value: 'NanChangShi' },
    { label: '景德镇市', value: 'JingDeZhenShi' },
    { label: '萍乡市', value: 'PingXiangShi' },
    { label: '九江市', value: 'JiuJiangShi' },
    { label: '新余市', value: 'XinYuShi' },
    { label: '鹰潭市', value: 'YingTanShi' },
    { label: '赣州市', value: 'GanZhouShi' },
    { label: '吉安市', value: 'JiAnShi' },
    { label: '宜春市', value: 'YiChunShi' },
    { label: '上饶市', value: 'ShangRaoShi' },
    { label: '抚州市', value: 'FuZhouShi' }
  ],
  ShanDongSheng: [
    { label: '济南市', value: 'JiNanShi' },
    { label: '青岛市', value: 'QingDaoShi' },
    { label: '淄博市', value: 'ZiBoShi' },
    { label: '枣庄市', value: 'ZaoZhuangShi' },
    { label: '东营市', value: 'DongYingShi' },
    { label: '烟台市', value: 'YanTaiShi' },
    { label: '潍坊市', value: 'WeiFangShi' },
    { label: '济宁市', value: 'JiNingShi' },
    { label: '泰安市', value: 'TaiAnShi' },
    { label: '日照市', value: 'RiZhaoShi' },
    { label: '莱芜市', value: 'LaiWuShi' },
    { label: '临沂市', value: 'LinYiShi' },
    { label: '德州市', value: 'DeZhouShi' },
    { label: '聊城市', value: 'LiaoChengShi' },
    { label: '滨州市', value: 'BinZhouShi' },
    { label: '菏泽市', value: 'HeZeShi' },
    { label: '威海市', value: 'WeiHaiShi' }
  ],
  HeNanSheng: [
    { label: '郑州市', value: 'ZhengZhouShi' },
    { label: '开封市', value: 'KaiFengShi' },
    { label: '洛阳市', value: 'LuoYangShi' },
    { label: '平顶山市', value: 'PingDingShanShi' },
    { label: '安阳市', value: 'AnYangShi' },
    { label: '鹤壁市', value: 'HeBiShi' },
    { label: '新乡市', value: 'XinXiangShi' },
    { label: '焦作市', value: 'JiaoZuoShi' },
    { label: '濮阳市', value: 'PuYangShi' },
    { label: '漯河市', value: 'LuoHeShi' },
    { label: '三门峡市', value: 'SanMenXiaShi' },
    { label: '南阳市', value: 'NanYangShi' },
    { label: '商丘市', value: 'ShangQiuShi' },
    { label: '信阳市', value: 'XinYangShi' },
    { label: '周口市', value: 'ZhouKouShi' },
    { label: '驻马店市', value: 'ZhuMaDianShi' },
    { label: '许昌市', value: 'XuChangShi' }
  ],
  HuBeiSheng: [
    { label: '武汉市', value: 'WuHanShi' },
    { label: '黄石市', value: 'HuangShiShi' },
    { label: '十堰市', value: 'ShiYanShi' },
    { label: '宜昌市', value: 'YiChangShi' },
    { label: '襄阳市', value: 'XiangYangShi' },
    { label: '鄂州市', value: 'EZhouShi' },
    { label: '荆门市', value: 'JingMenShi' },
    { label: '孝感市', value: 'XiaoGanShi' },
    { label: '黄冈市', value: 'HuangGangShi' },
    { label: '咸宁市', value: 'XianNingShi' },
    { label: '随州市', value: 'SuiZhouShi' },
    { label: '荆州市', value: 'JinZhouShi' }
  ],
  HuNanSheng: [
    { label: '长沙市', value: 'ChangShaShi' },
    { label: '株洲市', value: 'ZhuZhouShi' },
    { label: '湘潭市', value: 'XiangTanShi' },
    { label: '衡阳市', value: 'HenYangShi' },
    { label: '邵阳市', value: 'ShaoYangShi' },
    { label: '岳阳市', value: 'YueYangShi' },
    { label: '常德市', value: 'ChangDeShi' },
    { label: '张家界市', value: 'ZhangJiaJieShi' },
    { label: '益阳市', value: 'YiYangShi' },
    { label: '永州市', value: 'YongZhouShi' },
    { label: '怀化市', value: 'HuaiHuaShi' },
    { label: '郴州市', value: 'ChenZhouShi' }
  ],
  GuangDongSheng: [
    { label: '广州市', value: 'GuangZhouShi' },
    { label: '韶关市', value: 'ShaoGuanShi' },
    { label: '深圳市', value: 'ShenZhenShi' },
    { label: '珠海市', value: 'ZhuHaiShi' },
    { label: '汕头市', value: 'ShanTouShi' },
    { label: '佛山市', value: 'FoShanShi' },
    { label: '江门市', value: 'JiangMenShi' },
    { label: '湛江市', value: 'ZhanJiangShi' },
    { label: '茂名市', value: 'MaiMingShi' },
    { label: '肇庆市', value: 'ZhaoQingShi' },
    { label: '惠州市', value: 'HuiZhouShi' },
    { label: '梅州市', value: 'MeiZhouShi' },
    { label: '汕尾市', value: 'ShanWeiShi' },
    { label: '河源市', value: 'HeYuanShi' },
    { label: '阳江市', value: 'YangJiangShi' },
    { label: '清远市', value: 'QingYuanShi' },
    { label: '东莞市', value: 'DongWanShi' },
    { label: '潮州市', value: 'ChaoZhouShi' },
    { label: '揭阳市', value: 'JieYangShi' },
    { label: '云浮市', value: 'YunFuShi' },
    { label: '中山市', value: 'ZhongShanShi' }
  ],
  GuangXiZhuangZuZiZhiQu: [
    { label: '南宁市', value: 'NanNingShi' },
    { label: '柳州市', value: 'LiuZhouShi' },
    { label: '桂林市', value: 'GuiLinShi' },
    { label: '梧州市', value: 'WuZhouShi' },
    { label: '北海市', value: 'BeiHaiShi' },
    { label: '防城港市', value: 'FangChengGangShi' },
    { label: '钦州市', value: 'QinZhouShi' },
    { label: '贵港市', value: 'GuiGangShi' },
    { label: '玉林市', value: 'YuLinShi' },
    { label: '贺州市', value: 'HeZhouShi' },
    { label: '河池市', value: 'HeChiShi' },
    { label: '来宾市', value: 'LaiBinShi' },
    { label: '崇左市', value: 'ChongZuoShi' },
    { label: '百色市', value: 'BaiSeShi' }
  ],
  HaiNanSheng: [
    { label: '海口市', value: 'HaiKouShi' },
    { label: '三亚市', value: 'SanYaShi' },
    { label: '儋州市', value: 'Danzhou' },
    { label: '三沙市', value: 'SanShaShi' }
  ],
  SiChuanSheng: [
    { label: '成都市', value: 'ChengDouShi' },
    { label: '自贡市', value: 'ZiGongShi' },
    { label: '攀枝花市', value: 'PanZhiHuaShi' },
    { label: '泸州市', value: 'LuZhouShi' },
    { label: '德阳市', value: 'DeYangShi' },
    { label: '绵阳市', value: 'MianYangShi' },
    { label: '广元市', value: 'GuangYuanShi' },
    { label: '遂宁市', value: 'SuiNingShi' },
    { label: '乐山市', value: 'LeShanShi' },
    { label: '南充市', value: 'NanChongShi' },
    { label: '眉山市', value: 'MeiShanShi' },
    { label: '宜宾市', value: 'YiBinShi' },
    { label: '广安市', value: 'GuangAnShi' },
    { label: '达州市', value: 'DaZhouShi' },
    { label: '雅安市', value: 'YaAnShi' },
    { label: '巴中市', value: 'BaZhongShi' },
    { label: '内江市', value: 'NeiJiangShi' },
    { label: '资阳市', value: 'ZiYangeShi' }
  ],
  GuiZhouSheng: [
    { label: '贵阳市', value: 'GuiYangShi' },
    { label: '六盘水市', value: 'LiuPanShuiShi' },
    { label: '遵义市', value: 'ZunYiShi' },
    { label: '安顺市', value: 'AnShunShi' },
    { label: '毕节市', value: 'BiJieShi' },
    { label: '铜仁市', value: 'TongRenShi' }
  ],
  YunNanSheng: [
    { label: '昆明市', value: 'KunMingShi' },
    { label: '曲靖市', value: 'QuJingShi' },
    { label: '玉溪市', value: 'YuXiShi' },
    { label: '保山市', value: 'BaoShanShi' },
    { label: '昭通市', value: 'ZhaoTongShi' },
    { label: '丽江市', value: 'LiJiangShi' },
    { label: '普洱市', value: 'PuErShi' },
    { label: '临沧市', value: 'LinCangShi' }
  ],
  XiCangZiZhiQu: [
    { label: '拉萨市', value: 'LaSaShi' },
    { label: '昌都市', value: 'ChangDouShi' },
    { label: '山南市', value: 'ShanNanShi' },
    { label: '日喀则市', value: 'RiKaZeShi' },
    { label: '林芝市', value: 'LinZhiShi' }
  ],
  ShanXiShengB: [
    { label: '西安市', value: 'XiAnShi' },
    { label: '铜川市', value: 'TongChuanShi' },
    { label: '宝鸡市', value: 'BaoJiShi' },
    { label: '咸阳市', value: 'XianYangShi' },
    { label: '渭南市', value: 'WeiNanShi' },
    { label: '汉中市', value: 'HanZhongShi' },
    { label: '安康市', value: 'AnKangShi' },
    { label: '商洛市', value: 'ShangLuoShi' },
    { label: '延安市', value: 'YanAnShi' },
    { label: '榆林市', value: 'YuLinShi' }
  ],
  GanSuSheng: [
    { label: '兰州市', value: 'LanZhouShi' },
    { label: '嘉峪关市', value: 'JiaYuGuanShi' },
    { label: '金昌市', value: 'JinChangShi' },
    { label: '白银市', value: 'BaiYinShi' },
    { label: '天水市', value: 'TianShuiShi' },
    { label: '酒泉市', value: 'JiuQuanShi' },
    { label: '张掖市', value: 'ZhangYeShi' },
    { label: '武威市', value: 'WuWeiShi' },
    { label: '定西市', value: 'DingXiShi' },
    { label: '陇南市', value: 'LongNanShi' },
    { label: '平凉市', value: 'PinLiangShi' },
    { label: '庆阳市', value: 'QingYangShi' }
  ],
  QingHaiSheng: [
    { label: '西宁市', value: 'XiNingShi' },
    { label: '海东市', value: 'HaiDongShi' }
  ],
  NingXiaHuiZuZiZhiQu: [
    { label: '银川市', value: 'YinChuanShi' },
    { label: '石嘴山市', value: 'ShiZhuiShanShi' },
    { label: '吴忠市', value: 'WuZhongShi' },
    { label: '固原市', value: 'GuYuanShi' },
    { label: '中卫市', value: 'ZhongWeiShi' }
  ],
  XinJiangWeiWuErZiZhiQu: [
    { label: '乌鲁木齐市', value: 'WuLuMuQiShi' },
    { label: '克拉玛依市', value: 'KeLaMaYiShi' },
    { label: '吐鲁番市', value: 'TuLuFanShi' },
    { label: '哈密市', value: 'HaMiShi' }
  ]
}
export default dictionariesMap
